// DISCORD ACTIONS
export const GET_DC_SERVERS = "GET_DC_SERVERS";
export const GET_REQ = "GET_REQ";
export const GET_REQ_FAIL = "GET_REQ_FAIL";
export const CREATE_TEXT_CHANNEL = "CREATE_TEXT_CHANNEL";
export const FORM_VALIDATION = "FORM_VALIDATION";
export const DELETE_TEXT_CHANNEL = "DELETE_TEXT_CHANNEL";
export const ADD_SUBREDDIT_TO_TEXT_CHANNEL = "ADD_SUBREDDIT_TO_TEXT_CHANNEL";
export const SELECT_TEXT_CHANNEL = "SELECT_TEXT_CHANNEL";
export const SUCCESS_ALERT = "SUCCESS_ALERT";
export const GET_FOLLOWING_SUBREDDITS = "GET_FOLLOWING_SUBREDDITS";
export const SEARCH_FOLLOWING_LIST = "SEARCH_FOLLOWING_LIST";

// REDDIT ACTIONS
export const GET_TOKEN = "GET_TOKEN";
export const FETCH_USER_AUTH = "FETCH_USER_AUTH";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";
export const SEARCH_TEXT = "SEARCH_TEXT";
export const PAGINATION = "PAGINATION";
export const LIST_PAGINATION = "LIST_PAGINATION";
export const LOADING = "LOADING";
export const LOADED = "LOADED";
export const ADD_SUBREDDIT = "ADD_SUBREDDIT";
export const REMOVE_SUBREDDIT = "REMOVE_SUBREDDIT";
export const GET_SUBREDDITS = "GET_SUBREDDITS";
export const REFRESH_SUBREDDITS = "REFRESH_SUBREDDITS";
