# Generated by Django 3.1.2 on 2020-10-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddit',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='DiscordServer',
        ),
        migrations.DeleteModel(
            name='Subreddit',
        ),
    ]
