# Generated by Django 3.1.2 on 2020-10-17 13:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dashboarduser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='dashboarduser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='dashboarduser',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='dashboarduser',
            old_name='staff',
            new_name='is_superuser',
        ),
    ]
