# Generated by Django 3.1.2 on 2020-10-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0005_dashboarduser_subreddits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dashboarduser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
