# Generated by Django 3.1.2 on 2020-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0006_auto_20201029_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='banner_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
