# Generated by Django 3.1.2 on 2020-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0007_subreddit_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='icon_img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='over18',
            field=models.BooleanField(default=False),
        ),
    ]
