# Generated by Django 3.1.2 on 2020-11-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0008_auto_20201030_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordserver',
            name='subreddits',
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='text_channel',
        ),
        migrations.AlterField(
            model_name='dashboarduser',
            name='subreddits',
            field=models.ManyToManyField(blank=True, null=True, to='reddit_dashboard.Subreddit'),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discordserver',
            name='server_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='TextChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=250, unique=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit_dashboard.discordserver')),
            ],
        ),
    ]
