# Generated by Django 3.1.2 on 2020-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0009_auto_20201114_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='subreddits',
            field=models.ManyToManyField(blank=True, to='reddit_dashboard.Subreddit'),
        ),
    ]
