# Generated by Django 3.1.2 on 2020-11-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0012_textchannel_following_subreddits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_id', models.BigIntegerField(default=0, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('over_18', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentPosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_posts_posts', to='reddit_dashboard.posts')),
                ('textchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_posts_text_channel', to='reddit_dashboard.posts')),
            ],
        ),
    ]
