# Generated by Django 3.1.2 on 2020-11-18 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0014_posts_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentposts',
            name='SentDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentposts',
            name='textchannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_posts_text_channel', to='reddit_dashboard.textchannel'),
        ),
    ]
