# Generated by Django 3.1.2 on 2020-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0015_auto_20201118_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentposts',
            old_name='textchannel',
            new_name='text_channel',
        ),
    ]
