# Generated by Django 3.1.2 on 2020-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0016_auto_20201118_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='submission_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
