# Generated by Django 3.1.2 on 2020-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_dashboard', '0017_auto_20201118_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterUniqueTogether(
            name='sentposts',
            unique_together={('post', 'text_channel')},
        ),
    ]
